.\" This file is distributed under the same license as the qterm
.\" package.
.\" Copyright (C) LI Daobing <lidaobing@gmail.com>, 2008.
.\"
.TH "FQTERM" 1 "2008-10-13" "" ""
.SH NAME
fqterm \- BBS client for X Window System written in Qt

.SH "SYNOPSIS"
.B fqterm

.SH "DESCRIPTION"

.PP
This manual page documents briefly the \fBfqterm\fR command.

.PP
This manual page was written for the Debian distribution because the
original program does not have a manual page.

.PP
FQTerm is a BBS client for X Window System. It support telnet and ssh1
protocols. It also support zmodem, URL detect, mouse action.

.PP
Homepage: http://code.google.com/p/fqterm

.SH "SEE ALSO"
.BR qterm (1),
.BR pcmanx (1),
.BR telnet (1),
.BR ssh (1)
